### ISSUE TITLE
Remove source maps from build artifact

### ISSUE THREAD

**Issue by sechel** [embarq/safe-pipe#1]
There are source maps referenced in the release bundles. Please remove them they lead to warnings and confusion of debuggers such as
```text
DevTools failed to parse SourceMap: https://<server-name>:8444/home/embarq/.projects/safe-pipe/safe.pipe.js.map
```

**Comment by embarq** [comment]
https://github.com/embarq/safe-pipe/commit/e1f2c49522e38bc017bf46294f96c402e1bef5bd

**Comment by sechel** [comment]
Thanks 👍
