### ISSUE TITLE
Probably unneccessary redefinition of SecurityContext

### ISSUE THREAD

**Issue by lecanard539** [embarq/safe-pipe#26]
Here:

https://github.com/embarq/safe-pipe/blob/d55b405cc7daad7009397ac75ce83943abdf7218/projects/safe-pipe/src/lib/safe-pipe.pipe.ts#L11

Is a redefinition of SecurityContext from Angular which already defines this:

https://github.com/angular/angular/blob/3a60063a54d850c50ce962a8a39ce01cfee71398/packages/core/src/sanitization/security.ts#L18

You could probably reduce the weight of your pipe by using the Angular definition. Just FYI.

**Comment by embarq** [comment]
Hi, thanks for the info!
