### ISSUE TITLE
use - standalone

### ISSUE THREAD

**Issue by rbalet** [embarq/safe-pipe#46]
The migration to standalone component would be a real plus for this library

@embarq  I'd be glad to do a pull-request if you're ready to merge it :) Let me know

**Comment by embarq** [comment]
> The migration to standalone component would be a real plus for this library
> 
> 
> 
> @embarq  I'd be glad to do a pull-request if you're ready to merge it :) Let me know

@rbalet sure, let's go!

**Comment by rbalet** [comment]
@embarq Ok, there we go.

I'll made multiple merge request in case you'd like to publish them one after the other.

**Comment by rbalet** [comment]
@embarq You can then safely remove all of them 

![image](https://github.com/embarq/safe-pipe/assets/44493964/03b1bfd6-a9eb-4a60-b61a-8f57037008b4)

Cheers

**Comment by embarq** [comment]
Thanks to @rbalet the [safe-pipe@3.0.4](https://www.npmjs.com/package/safe-pipe/v/3.0.3) is now online. GJ!
